<?php
namespace Pronamic\Twinfield\Secure;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-20 at 08:44:43.
 */
class LoginTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Login
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        include(dirname(__FILE__)."/../../../../accountdetails.php");
        $config = new Config();
        $config->setCredentials($username, $password, $organisation, $office);
        
        $this->object = new Login($config);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Pronamic\Twinfield\Secure\Login::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        $this->assertTrue($this->object->process());
    }

    /**
     * @covers Pronamic\Twinfield\Secure\Login::getHeader
     * @todo   Implement testGetHeader().
     */
    public function testGetHeader()
    {
        $header = $this->object->getHeader();
        $this->assertTrue($header instanceof \SoapHeader);
    }

    /**
     * @covers Pronamic\Twinfield\Secure\Login::getClient
     * @todo   Implement testGetClient().
     */
    public function testGetClient()
    {
        $client = $this->object->getClient();
        $this->assertTrue($client instanceof \Pronamic\Twinfield\SoapClient);
    }
}
